from __future__ import annotations

from pathlib import Path

from .data_preprocessing import clean_dataset, describe_dataset, get_default_dataset_path, load_data, save_processed_data
from .model_pipeline import save_model, train_and_evaluate

MODEL_PATH = Path(__file__).resolve().parents[2] / "models" / "property_price_model.joblib"
REPORT_PATH = Path(__file__).resolve().parents[2] / "reports" / "model_evaluation_report.md"


def main() -> None:
    dataset_path = get_default_dataset_path()
    df = load_data(dataset_path)
    cleaned = clean_dataset(df)
    describe_dataset(cleaned)
    save_processed_data(cleaned)

    model, metrics = train_and_evaluate(cleaned)

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    save_model(model, str(MODEL_PATH))

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    report = f"""# Model Evaluation Report

## Dataset
- Rows: {len(cleaned)}
- Features: {cleaned.shape[1] - 1}
- Target: price

## Performance Metrics
- MAE: ${metrics['MAE']:,.2f}
- MSE: ${metrics['MSE']:,.2f}
- RMSE: ${metrics['RMSE']:,.2f}
- R² Score: {metrics['R2']:.4f}

## Notes
This report was generated by the residential property price prediction project. The model uses a preprocessing pipeline with one-hot encoding and a gradient boosting regressor.
"""
    REPORT_PATH.write_text(report, encoding="utf-8")

    print(f"Model saved to: {MODEL_PATH}")
    print(f"Evaluation report saved to: {REPORT_PATH}")
    print(f"MAE: ${metrics['MAE']:,.2f}")
    print(f"RMSE: ${metrics['RMSE']:,.2f}")
    print(f"R2: {metrics['R2']:.4f}")


if __name__ == "__main__":
    main()
